config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'meetings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  has_one_attached :resume
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: {minimum: 4, maximum: 16}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :meetings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @meetings = Meeting.where(name: current_user.user_name).or(Meeting.where(user: current_user))
  end
  
  def show
  end

  def new
    @meeting = Meeting.new
  end

  def edit
  end

  def create
    u = User.find_by(:user_name => params[:meeting][:user_name])
    @meeting = Meeting.create(:user_id => u.id, :start_time => params[:meeting][:start_time], :end_time => params[:meeting][:end_time], :name => params[:meeting][:name], :resume => params[:meeting][:resume])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        UserMailer.with(:user_id => u.id).reminder_email.deliver_later(wait_until: @meeting.start_time - 30.minutes)
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        UserMailer.with(:user_id => u.id).updation_email.deliver_later(wait_until: @meeting.start_time - 30.minutes)
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def meeting_params
      params.permit(:name, :start_time, :end_time, :user_id, :user_name, :resume)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>Scheduly</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<header class="navbar">
		<%= link_to  'Scheduly', '/' , class: "navbar-logo"%>
		<% if user_signed_in? %>
		<%= link_to "New Meeting", new_meeting_path, class: "navbar-links" %>
		<%= link_to "Logout", destroy_user_session_path, method: :delete , class: "navbar-links"%>
		<% else %>
		<%= link_to "Login", new_user_session_path, class: "navbar-links" %>
		<%= link_to "Register", new_user_registration_path ,class: "navbar-links" %>
		<%end%>
	</header>

	<%= yield %>
</body>

</html>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
<% if meeting.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

  <ul>
    <% meeting.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div class="field">
  <%= form.label :start_time %>
  <%= form.datetime_field :start_time %>
</div>

<div class="field">
  <%= form.label :end_time %>
  <%= form.datetime_field :end_time %>
</div>

<div class="field">
  <%= form.label :user_name %>
  <%= form.text_field :user_name %>
</div>

<div class = field>
  <%= form.label :resume %>
  <%= form.file_field :resume%>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings of <%= current_user.user_name %></h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Start time</th>
            <th>End time</th>
            <th>User</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @meetings.each do |meeting| %>
        <tr>
            <td><%= meeting.name %></td>
            <td><%= meeting.start_time %></td>
            <td><%= meeting.end_time %></td>
            <td><%= meeting.user.user_name %></td>
            <td><%= link_to 'Show', meeting %></td>
            <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
            <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @meeting.user.user_name %>
</p>

<p>
  <strong>Resume: </strong>
  <%= link_to "Donwload", @meeting.resume %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>